import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/global/navigation/Navbar";
import { ThemeProvider } from "@/providers/ThemProvider";
import ThemeChanger from "@/utils/ThemeChanger";

const fontStyle = Hind_Siliguri({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={fontStyle.className}>
        <ThemeProvider>
          <ThemeChanger>
            <Navbar>{children}</Navbar>
          </ThemeChanger>
        </ThemeProvider>
      </body>
    </html>
  );
}
